# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eH5DchxE3ukKZHJVNhOniYvzFjC4fXMM
"""

!pip install streamlit

import streamlit as st

# Chatbot logic or import it from another script
def chatbot_response(user_input):
    # Replace with your chatbot's logic
    if user_input:
        return f"Bot: You said '{user_input}'. How can I help you further?"
    return "Bot: Hello! Ask me something."

# Streamlit UI
st.title("Chatbot on Streamlit")
user_input = st.text_input("You: ", "")

if st.button("Send"):
    response = chatbot_response(user_input)
    st.text_area("Response", response, height=200)